---
- include_tasks:        '../tasks/dependencies.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/disable_services.yml'
- include_tasks:        '../tasks/stop_services.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 disable_services_result.changed
                        or template_files_result.changed
